package clasesPojo;
// Generated 04-mar-2020 12:52:09 by Hibernate Tools 4.3.1

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String nombreusuario;
     private String password;
     private String nombrecompleto;
     private String telefono;
     

    public Empleado() {
    }

	
    public Empleado(String nombreusuario, String password, String nombrecompleto, String telefono) {
        this.nombreusuario = nombreusuario;
        this.password = password;
        this.nombrecompleto = nombrecompleto;
        this.telefono = telefono;
    }
      
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombrecompleto() {
        return this.nombrecompleto;
    }
    
    public void setNombrecompleto(String nombrecompleto) {
        this.nombrecompleto = nombrecompleto;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
   

    @Override
    public String toString() {
        return "Empleado: Nombre de usuario= " + nombreusuario + " --- Password= " + password + " --- Nombre completo= " + nombrecompleto + " --- Telefono= " + telefono + "\n";
    }
}


