package clasesPojo;
// Generated 04-mar-2020 12:52:09 by Hibernate Tools 4.3.1

import enums.TipoEvento;

/**
 * Historial generated by hbm2java
 */
public class Historial  implements java.io.Serializable {


     private Integer idEvento;
     private Empleado empleado;
     private TipoEvento tipo;
     private String fechahora;

    public Historial() {
    }

    public Historial(Integer idEvento, Empleado empleado, TipoEvento tipo, String fechahora) {
       this.idEvento = idEvento;
       this.empleado = empleado;
       this.tipo = tipo;
       this.fechahora = fechahora;
    }
   
    public Integer getIdevento() {
        return this.idEvento;
    }
    
    public void setIdevento(Integer idevento) {
        this.idEvento = idevento;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public TipoEvento getTipo() {
        return this.tipo;
    }
    
    public void setTipo(TipoEvento tipo) {
        this.tipo = tipo;
    }
    public String getFechahora() {
        return this.fechahora;
    }
    
    public void setFechahora(String fechahora) {
        this.fechahora = fechahora;
    }

    @Override
    public String toString() {
        return "Historial: Id Evento= " + idEvento + " --- Empleado= " + empleado.getNombreusuario() + " --- Tipo= " + tipo + " --- Fecha/Hora= " + fechahora + '\n';
    }

    


}


