package clasesPojo;
// Generated 04-mar-2020 12:52:09 by Hibernate Tools 4.3.1

import enums.Prioridad;

/**
 * Incidencia generated by hbm2java
 */
public class Incidencia  implements java.io.Serializable {


     private int idincidencia;
     private Empleado empleadoOrigen;
     private Empleado empleadoDestino;
     private String fechahora;
     private String detalle;
     private Prioridad prioridad;

    public Incidencia() {
    }

    public Incidencia(int idincidencia, Empleado empleadoOrigen, Empleado empleadoDestino, String fechahora, String detalle, Prioridad prioridad) {
       this.idincidencia = idincidencia;
       this.empleadoOrigen = empleadoOrigen;
       this.empleadoDestino = empleadoDestino;
       this.fechahora = fechahora;
       this.detalle = detalle;
       this.prioridad = prioridad;
    }
   
    public int getIdincidencia() {
        return this.idincidencia;
    }
    
    public void setIdincidencia(int idincidencia) {
        this.idincidencia = idincidencia;
    }
    public Empleado getEmpleadoOrigen() {
        return this.empleadoOrigen;
    }
    
    public void setEmpleadoOrigen(Empleado empleadoOrigen) {
        this.empleadoOrigen = empleadoOrigen;
    }
    public Empleado getEmpleadoDestino() {
        return this.empleadoDestino;
    }
    
    public void setEmpleadoDestino(Empleado empleadoDestino) {
        this.empleadoDestino = empleadoDestino;
    }
    public String getFechahora() {
        return this.fechahora;
    }
    
    public void setFechahora(String fechahora) {
        this.fechahora = fechahora;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public Prioridad getTipo() {
        return this.prioridad;
    }
    
    public void setTipo(Prioridad prioridad) {
        this.prioridad = prioridad;
    }

    @Override
    public String toString() {
        return "Incidencia: Id incidencia= " + idincidencia + " --- Empleado Origen= " + empleadoOrigen.getNombreusuario() + " --- Empleado Destino= " + empleadoDestino.getNombreusuario() + " --- Fecha/Hora= " + fechahora + " --- Detalle= " + detalle + " --- Prioridad= " + prioridad + "\n";
    }

    
    

}


